### ISSUE TITLE
Support IntelliJ IDEA 2021.2

### ISSUE THREAD

**Issue by lagivan** [marcelhillesheim/outSPARQL#1]
The plugin is incompatible with the latest release of IntelliJ IDEA 2021.2.

**Comment by marcelhillesheim** [comment]
Yeah. The problem was that the build number was limited to 211.* and 2021.2 has 212.* as build number. Removed the restriction, which may cause problems with updates in the future? But the plugin verifier should deal with that i guess. 

Updated the code, but wanted to run the plugin verifier before publishing. Ran into an issue with the plugin verifier(which i havent resolved yet). Long story short: update will be probably published tomorrow.

**Comment by marcelhillesheim** [comment]
Update got approved and is now available for download. If there are any further issues report them as i am currently not actively using the plugin myself.
